Repository ant-design/ant-design-mobile, pull requests merged in 2018-05, with the labels that each got.

#2506 fix(textarea-item)
  components/textarea-item/index.tsx
Labels: In Progress

#2509 fix: upgrade rmc-feedback to 2.x
  package.json
Labels: In Progress

#2510 fix: style of <SearchBar/>
  components/search-bar/style/index.less
Labels: In Progress

#2523 docs: fix typo
  components/icon/index.en-US.md
  components/list/demo/form.md
Labels: In Progress

#2527 demo: add use of listview component nested with tabbar, close #2455
  components/tab-bar/__tests__/__snapshots__/demo.test.js.snap
  components/tab-bar/demo/listview-tabbar.md
  site/bisheng.common.config.js
Labels: In Progress

#2508 fix(input-item): value.substring is not a function
  components/input-item/CustomInput.tsx
  components/input-item/__tests__/__snapshots__/demo.test.js.snap
  components/input-item/demo/basic.md
  components/input-item/demo/money.md
  components/input-item/index.tsx
Labels: In Progress

#2530 fix(Accordion): make aria-expanded prop valid in preact, close #2491
  package.json
Labels: In Progress

#2532 fix(input-item): cursor dislocation in UC browser
  components/input-item/index.tsx
Labels: In Progress

#2537 fix(input-item): user experience regression on non-mutate control
  components/input-item/index.tsx
Labels: In Progress

#2408 feat: add focus method #2381
  components/button/index.native.tsx
  components/input-item/Input.native.tsx
  components/input-item/index.en-US.md
  components/input-item/index.native.tsx
  components/input-item/index.zh-CN.md
Labels: In Progress, type: feature, type: react native

#2511 fix: Picker && SearchBar LocalProvider Context
  components/locale-provider/__tests__/__snapshots__/demo.test.js.snap
  components/picker/index.tsx
  components/search-bar/index.tsx
Labels: In Progress

#2538 Fix(inputitem): add wai-aria suppport for the money type InputItem
  components/input-item/CustomInput.tsx
  components/input-item/CustomKeyboard.tsx
  components/input-item/Portal.tsx
  components/input-item/__tests__/__snapshots__/demo.test.js.snap
  components/input-item/index.tsx
  components/input-item/locale/en_US.tsx
  components/input-item/locale/ru_RU.tsx
  components/input-item/locale/sv_SE.tsx
  components/input-item/locale/zh_CN.tsx
  components/locale-provider/__tests__/__snapshots__/demo.test.js.snap
  components/modal/style/Dialog.less
Labels: In Progress

#2550 feat(input-item): add "moneyKeyboardWrapProps"
  components/input-item/CustomInput.tsx
  components/input-item/CustomKeyboard.tsx
  components/input-item/PropsType.tsx
  components/input-item/demo/money.md
  components/input-item/index.en-US.md
  components/input-item/index.tsx
  components/input-item/index.zh-CN.md
Labels: In Progress

#2551 feat(input-item): add "onVirtualKeyboardConfirm" callback
  components/input-item/CustomInput.tsx
  components/input-item/PropsType.tsx
  components/input-item/demo/money.md
  components/input-item/index.en-US.md
  components/input-item/index.tsx
  components/input-item/index.zh-CN.md
Labels: In Progress

#2554 Release/2.1.9
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/input-item/demo/money.md
  components/locale-provider/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: In Progress

#2358 input-item: Add a clear button for android platform
  components/input-item/index.native.tsx
  components/input-item/style/index.native.tsx
Labels: In Progress, type: react native

#2568 Fix(InputItem): avoid error focus in aria mode
  components/input-item/CustomKeyboard.tsx
  components/input-item/style/index.less
Labels: In Progress

#2570 bump 2.1.10
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: In Progress

#2577 Fix(InputItem): remove the unknown-prop warning
  components/input-item/index.tsx
Labels: In Progress

#2594 demo(pull-to-refresh): update damping prop api, close #2542
  components/pull-to-refresh/__tests__/__snapshots__/demo.test.js.snap
  components/pull-to-refresh/demo/basic.md
  components/pull-to-refresh/index.en-US.md
  components/pull-to-refresh/index.zh-CN.md
Labels: In Progress
