Repository ant-design/ant-design-mobile, pull requests merged in 2018-03, with the labels that each got.

#2347 fix: modal.alert content align=center
  components/modal/AlertContainer.native.tsx
Labels: In Progress, type: react native

#2390 docs(readme): add cn mirror link
  README.zh-CN.md
Labels: In Progress, type: document

#2403 fix: input type money
  components/input-item/CustomInput.tsx
  components/input-item/index.tsx
Labels: In Progress

#2404 revert(button): rest props
  components/button/index.native.tsx
Labels: In Progress
