Repository ant-design/ant-design-mobile, pull requests merged in 2021-11, with the labels that each got.

#4319 enhance: (Form) normal item collects sub noStyle items errors
  src/components/form/context.tsx
  src/components/form/form-item.tsx
Labels: enhancement

#4358 feat: add VirtualInput component
  config/components.ts
  src/components/input/index.en.md
  src/components/input/index.zh.md
  src/components/number-keyboard/number-keyboard.tsx
  src/components/virtual-input/demos/demo1.tsx
  src/components/virtual-input/index.en.md
  src/components/virtual-input/index.tsx
  src/components/virtual-input/index.zh.md
  src/components/virtual-input/virtual-input.less
  src/components/virtual-input/virtual-input.tsx
  src/index.ts
  src/utils/native-props.ts
Labels: feature

#4362 feat: add new component CapsuleTabs and JumboTabs
  config/components.ts
  src/components/capsule-tabs/capsule-tabs.less
  src/components/capsule-tabs/capsule-tabs.tsx
  src/components/capsule-tabs/demos/index.tsx
  src/components/capsule-tabs/index.en.md
  src/components/capsule-tabs/index.ts
  src/components/capsule-tabs/index.zh.md
  src/components/jumbo-tabs/demos/index.tsx
  src/components/jumbo-tabs/index.en.md
  src/components/jumbo-tabs/index.ts
  src/components/jumbo-tabs/index.zh.md
  src/components/jumbo-tabs/jumbo-tabs.less
  src/components/jumbo-tabs/jumbo-tabs.tsx
  src/components/scroll-mask/demos/index.tsx
  src/components/scroll-mask/index.en.md
  src/components/scroll-mask/index.ts
  src/components/scroll-mask/index.zh.md
  src/components/scroll-mask/scroll-mask.less
  src/components/scroll-mask/scroll-mask.tsx
  src/components/tabs/demos/index.tsx
  src/components/tabs/index.en.md
  src/components/tabs/index.ts
  src/components/tabs/index.zh.md
  src/components/tabs/tabs.tsx
  src/index.ts
  src/utils/use-tab-list-scroll.ts
Labels: feature

#4374 fix: (Picker) `context` param in `onSelect` and `onConfirm` return outdated data
  src/components/picker/demos/index.tsx
  src/components/picker/picker.tsx
  src/utils/use-lazy-memo.tsx
Labels: bug

#4381 feat: (PickerView) onChange add context param
  src/components/picker-view/demos/basic.tsx
  src/components/picker-view/index.en.md
  src/components/picker-view/index.ts
  src/components/picker-view/index.zh.md
  src/components/picker-view/picker-view.tsx
  src/components/picker-view/use-picker-value-extend.tsx
  src/components/picker/demos/index.tsx
  src/components/picker/index.en.md
  src/components/picker/index.ts
  src/components/picker/index.zh.md
  src/components/picker/picker.tsx
  src/components/selector/demos/demo1.tsx
  src/components/selector/index.en.md
  src/components/selector/index.zh.md
  src/components/selector/selector.tsx
  src/components/tree-select/index.en.md
  src/components/tree-select/index.zh.md
  src/components/tree-select/tree-select.tsx
Labels: feature

#4417 feat: add FloatingBubble
  config/components.ts
  src/components/floating-bubble/demos/demo.tsx
  src/components/floating-bubble/floating-bubble.less
  src/components/floating-bubble/floating-bubble.tsx
  src/components/floating-bubble/index.en.md
  src/components/floating-bubble/index.ts
  src/components/floating-bubble/index.zh.md
  src/index.ts
Labels: feature
