Repository ant-design/ant-design-mobile, pull requests merged in 2021-09, with the labels that each got.

#3942 Swiper
  config/config.ts
  package.json
  src/components/swiper/demos/demo1.less
  src/components/swiper/demos/demo1.tsx
  src/components/swiper/index.md
  src/components/swiper/index.ts
  src/components/swiper/page-indicator.less
  src/components/swiper/page-indicator.tsx
  src/components/swiper/swiper-item.tsx
  src/components/swiper/swiper.less
  src/components/swiper/swiper.tsx
  src/index.ts
  src/utils/attach-properties-to-component.ts
  yarn.lock
Labels: feature

#3961 feat: Switch with content
  src/components/switch/demos/index.tsx
  src/components/switch/index.md
  src/components/switch/switch.less
  src/components/switch/switch.tsx
Labels: feature

#3966 feat: IndexBar ref
  src/components/index-bar/demos/demo2.tsx
  src/components/index-bar/index-bar.tsx
  src/components/index-bar/index.md
  src/components/index-bar/index.ts
Labels: feature

#3970 feat: Checkbox custom icon
  src/components/checkbox/checkbox.less
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/demos/index.tsx
  src/components/checkbox/index.md
Labels: feature

#3994 feat: Picker add `title` prop
  src/components/picker/demos/index.tsx
  src/components/picker/index.md
  src/components/picker/picker.less
  src/components/picker/picker.tsx
Labels: feature

#3997 feat: NavBar
  config/config.ts
  src/components/nav-bar/demos/index.less
  src/components/nav-bar/demos/index.tsx
  src/components/nav-bar/index.md
  src/components/nav-bar/index.ts
  src/components/nav-bar/nav-bar.less
  src/components/nav-bar/nav-bar.tsx
  src/index.ts
Labels: feature

#3999 fix: custom Navbar back icon failure
  src/components/nav-bar/nav-bar.less
  src/components/nav-bar/nav-bar.tsx
Labels: bug

#4012 refactor: re-implement Loading with svg
  docs/components/icon/demo-all.tsx
  src/components/button/button.tsx
  src/components/button/demos/index.tsx
  src/components/image-uploader/preview-item.tsx
  src/components/infinite-scroll/demos/content.tsx
  src/components/infinite-scroll/infinite-scroll.tsx
  src/components/loading/demos/index.tsx
  src/components/loading/index.md
  src/components/loading/loading.less
  src/components/loading/loading.tsx
Labels: enhancement

#4039 feat: add PickerView component
  .dumi/theme/builtins/Previewer.less
  config/components.ts
  src/components/cascade-picker/cascade-picker.tsx
  src/components/cascade-picker/index.ts
  src/components/cascade-picker/prompt.tsx
  src/components/date-picker/index.md
  src/components/picker-view/column.tsx
  src/components/picker-view/demos/basic.tsx
  src/components/picker-view/index.md
  src/components/picker-view/index.ts
  src/components/picker-view/picker-view.less
  src/components/picker-view/picker-view.tsx
  src/components/picker-view/use-columns.tsx
  src/components/picker/demos/cascade-picker-demo.tsx
  src/components/picker/demos/date-picker-demo.tsx
  src/components/picker/demos/index.tsx
  src/components/picker/index.md
  src/components/picker/index.ts
  src/components/picker/picker.less
  src/components/picker/picker.tsx
  src/index.ts
Labels: feature
