Repository ant-design/ant-design-mobile, pull requests merged in 2025-07, with the labels that each got.

#6906 fix: iso date base date string
  src/components/date-picker/date-picker-week-utils.ts
  src/components/date-picker/tests/date-picker.test.tsx
Labels: lgtm

#6897 feat: 默认禁用光标位置可调整，支持通过 touchmove 调整光标位置
  src/components/virtual-input/demos/demo1.tsx
  src/components/virtual-input/index.zh.md
  src/components/virtual-input/tests/virtual-input.test.tsx
  src/components/virtual-input/virtual-input.less
  src/components/virtual-input/virtual-input.tsx
Labels: size:XL, lgtm

#6924 Feat/add props custom cell classname
  src/components/calendar/calendar.en.md
  src/components/calendar/calendar.tsx
  src/components/calendar/calendar.zh.md
  src/components/calendar/demos/demo6.less
  src/components/calendar/demos/demo6.tsx
  src/components/calendar/tests/calendar.test.tsx
Labels: feature, size:L, lgtm
